### ISSUE TITLE
12 hour times with am/pm

### ISSUE THREAD

**Issue by shonnarenae** [sergant210/myCalendar#10]
Is there a way to add AM/PM for 12 hour clocks in the edit event window? I tried adding A into axisFormat but it didn't do anything.

**Comment by sergant210** [comment]
Only to edit the source [js file](https://github.com/sergant210/myCalendar/blob/master/assets/components/mycalendar/js/default.js#L275).
You can copy this file, edit as you need and set new js file name to the mycalendar setting ''default_js" .

**Comment by shonnarenae** [comment]
Worked perfectly, thank you! I did that and simply added an A to the line you highlighted.
