### ISSUE TITLE
Не большой баг репорт , немного затрудняет использование 

### ISSUE THREAD

**Issue by shectermen** [sergant210/myCalendar#3]
1) ставишь запись на 2 мин, сохраняешь, блок получается на 60 мин... 

2) на одно и то же время можно создавать несколько записей (как и в гугле), но из-за того что не можешь нормально выстроить время не получается...  

3) нету поиска. 

4) рабочее поле маленькое 

5) время можено выставить чтобы отображалось с 10 до 03 ночи

6) когда создаешь запись в левом нижнем углу есть галочка "целый день". Но если ее нажимаешь эта запись в календаре отображается маленькой записью в самом вверху, ее не видно

7) Что бы удалить запись, нужно нажать "крестик" в правом вернем углу, но когда создаешь несколько записей на одно время они "накладываются" друг на друга. и закрывают это крестик

8) в заголовке прописывается ограниченное количество символов
то есть часть информации нужно прописывать в описании, но то что пишется в описании не прописывается в календаре

9) еще в гугле была возможность повторить событие - например создали сегодня и продублировали на месяц вперед)

надеюсь помог , большое спасибо за разработку

**Comment by sergant210** [comment]
> 1) ставишь запись на 2 мин, сохраняешь, блок получается на 60 мин...
> 2) на одно и то же время можно создавать несколько записей (как и в гугле), но из-за того что не можешь нормально выстроить время не получается..

Минимальная длительность события 30 мин. Если задать меньше, то конечное время выставляется согласно параметра defaultDuration. По-умолчанию, он 60 мин. Если делать меньше 30 мин., то текста не видно.
> 4) рабочее поле маленькое 

Не совсем понял, что имеется ввиду.
> 5) время можено выставить чтобы отображалось с 10 до 03 ночи

Это как?
> 6) когда создаешь запись в левом нижнем углу есть галочка "целый день". Но если ее нажимаешь эта запись в календаре отображается маленькой записью в самом вверху, ее не видно

А как должно быть? Посмотри в Google, там также. Это стандарт.
> 7) Что бы удалить запись, нужно нажать "крестик" в правом вернем углу, но когда создаешь несколько записей на одно время они "накладываются" друг на друга. и закрывают это крестик

В диалог добавлю кнопку для удаления.
> 8) в заголовке прописывается ограниченное количество символов
то есть часть информации нужно прописывать в описании, но то что пишется в описании не прописывается в календаре

Вот [решение](https://modx.pro/components/5304-mycalendar-simple-calendar/#comment-38875). Добавлю по-умолчанию в следующей версии.
> 9) еще в гугле была возможность повторить событие - например создали сегодня и продублировали на месяц вперед)

В myCalendar такого функционала нет. Он есть в [fullCalendar](https://modx.pro/solutions/5580-fullcalendar-calendar-with-great-potential/).

Для информации. За отображение событий полностью отвечает javascript-библиотека fullCalendar. Я только подношу патроны (события). Информацию о возможностях этой библиотеки можно посмотреть [тут](http://fullcalendar.io/).

**Comment by shectermen** [comment]
спасибо за ответ !


Суббота, 16 мая 2015, 23:01 -07:00 от Sergey Shlokov <notifications@github.com>:
>>1) ставишь запись на 2 мин, сохраняешь, блок получается на 60 мин...
>>2) на одно и то же время можно создавать несколько записей (как и в гугле), но из-за того что не можешь нормально выстроить время не получается..
>Минимальная длительность события 30 мин. Если задать меньше, то конечное время выставляется согласно параметра defaultDuration. По-умолчанию, он 60 мин. Если делать меньше 30 мин., то текста не видно.
>>4) рабочее поле маленькое 
>Не совсем понял, что имеется ввиду.
>>5) время можено выставить чтобы отображалось с 10 до 03 ночи
>Это как?
>>6) когда создаешь запись в левом нижнем углу есть галочка "целый день". Но если ее нажимаешь эта запись в календаре отображается маленькой записью в самом вверху, ее не видно
>А как должно быть? Посмотри в Google, там также. Это стандарт.
>>7) Что бы удалить запись, нужно нажать "крестик" в правом вернем углу, но когда создаешь несколько записей на одно время они "накладываются" друг на друга. и закрывают это крестик
>В диалог добавлю кнопку для удаления.
>>8) в заголовке прописывается ограниченное количество символов
>>то есть часть информации нужно прописывать в описании, но то что пишется в описании не прописывается в календаре
>Вот  решение . Добавлю по-умолчанию в следующей версии.
>>9) еще в гугле была возможность повторить событие - например создали сегодня и продублировали на месяц вперед)
>В myCalendar такого функционала нет. Он есть в  fullCalendar .
>Для информации. За отображение событий полностью отвечает javascript-библиотека fullCalendar. Я только подношу патроны (события). Информацию о возможностях этой библиотеки можно посмотреть  тут .
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Сергей Алпеев
salpeev@mail.ru
