### ISSUE TITLE
myCalendar not showing on iPad or Mobile

### ISSUE THREAD

**Issue by SidewaysCreative** [sergant210/myCalendar#8]
Hey,

I am using myCalendar on one of my current projects and it is working brilliantly on desktop. However for some reason the calendar isn't showing on mobiles and tablets?

Im using modx 2.4.2

and my snippet call is:

[[+modx.user.id:memberof=`Administrator`:then=`[[!myCalendar? &defaultView=`month` &instance=`calendar1`]]`:else=`[[!myCalendar? &defaultView=`month` &instance=`calendar2` &editable=`false` &readOnly=`1`]]`]]

**Comment by sergant210** [comment]
Described problem is not detected. The calendar works well on my mobile.

**Comment by SidewaysCreative** [comment]
Thank for getting back to me @sergant210 I have now solved the bug that was with another thing I was using on the website apologies!
